name: logbook-dev

services:
  logbook:
    build: ./
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=logbook
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - .:/usr/src
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - logbook-network
    working_dir: /usr/src
    depends_on:
      - postgres

  postgres:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=logbook
    ports:
      - 5432:5432
    restart: always
    networks:
      - logbook-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  logbook-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
